version: "3.8"

services:
  server:
    build: ./server
    container_name: server
    restart: always
    ports:
      - 80:80
      - 443:443

networks:
  default:
    external: true
    name: server-network