version: "3.8"

services:
  server:
    build: ./server
    container_name: server
    restart: always
    ports:
      - 80:80
      - 443:443

  mongo:
    build: ./database/mongo
    restart: unless-stopped
    container_name: mongodb
    ports:
      - 27017:27017
    env_file:
      - ./database/mongo/.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: MONGO_USER_ROOT
      MONGO_INITDB_ROOT_PASSWORD: MONGO_USER_PASSWORD
    volumes:
      - ./database/mongo/db:/data/db
  
  orisistem:
    build: ./auth
    container_name: authentication
    restart: unless-stopped
    command: uvicorn main:app --port 5000 --host 0.0.0.0
    ports:
      - 5000:5000
    env_file:
      - ./auth/app/.env
    volumes:
      - ./auth/app:/oriapp/app

networks:
  default:
    external: true
    name: server-network