version: "3.8"

services:
  server:
    build: ./server
    container_name: server
    restart: always
    ports:
      - 80:80
      - 443:443

  mongo:
    image: mongo
    restart: unless-stopped
    container_name: mongo
    ports:
      - 27017:27017
    env_file:
      - ./database/.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: MONGO_USER_ROOT
      MONGO_INITDB_ROOT_PASSWORD: MONGO_USER_PASSWORD
    volumes:
      - ./database/mongodb:/data/db
  
  orisistem:
    build: ./auth
    container_name: auth
    restart: unless-stopped
    command: gunicorn --bind 0.0.0.0:5000 -w 3 main:app
    ports:
      - 5000:5000
    env_file:
      - ./app/.env
    volumes:
      - ./app:/oriapp/app

networks:
  default:
    external: true
    name: server-network